# 1. Imports

In [29]:
# importing other dependencies
import numpy as np

In [1]:
# importing PyTorch
import torch

# checks whether MPS is available
print(torch.backends.mps.is_available())

# this ensures that the current current PyTorch installation was built with MPS activated.
print(torch.backends.mps.is_built())

# setting the device to "mps" instead of default "cpu"
device = torch.device("mps" if torch.backends.mps.is_available else "cpu")

True
True


# 2. Playing around with Tensors

## 2.1 Creating Tensors

In [13]:
# creates a custom tensor from the given list of imputs (like numpy)
x = torch.IntTensor([1, 2, 3])
print(x)

tensor([1, 2, 3], dtype=torch.int32)


In [15]:
# creates a custom tensor from the given list of imputs (like numpy)
x = torch.FloatTensor([1., 2., 3.])
print(x)
# by default, Tensors have the datatype 'Float' imbedded

tensor([1., 2., 3.])


In [3]:
# creates an empty tensor of size 3
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [4]:
# a 2D tensor of size (2,3)
x = torch.empty(2,3)
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00, -1.5846e+29]])


In [5]:
# tensor of size (2,3) with random initialization
x = torch.rand(2,3)
print(x)

tensor([[0.2355, 0.5542, 0.1524],
        [0.8502, 0.3206, 0.9898]])


In [10]:
# tensor of size (2,3) with 'zero' initialization
x = torch.zeros(2,3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [11]:
# tensor of size (2,3) with 'ones' initialization
x = torch.ones(2,3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


## 2.2 Managing the Data Types

In [16]:
# creates a tensor of size (2,2) consisting of ones, with datatype 'int64'
x = torch.ones(2,2, dtype=torch.int64)
print(x)
print(x.dtype)

tensor([[1, 1],
        [1, 1]])
torch.int64


In [17]:
# creates a tensor of size (2,2) consisting of ones, with datatype 'float64'
x = torch.ones(2,2, dtype=torch.float64)
print(x)
print(x.dtype)

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)
torch.float64


## 2.3 Mangaging Size

In [18]:
x = torch.tensor([[1, 2],
                [3, 4]])
print(x.size())

torch.Size([2, 2])


In [19]:
n,m = x.size()
print(n,m)

2 2


## 2.4 Operations

In [21]:
x = torch.rand(2, 2)
print(x)
y = torch.rand(2, 2)
print(y)

tensor([[0.3378, 0.5954],
        [0.7578, 0.2830]])
tensor([[0.8573, 0.5410],
        [0.8054, 0.5486]])


In [22]:
# element-wise operations on x and y

# addition
z = x + y
# torch.add(x,y)
print(z)

# subtraction
z = x - y
# z = torch.sub(x, y)
print(z)

# multiplication
z = x * y
# z = torch.mul(x,y)
print(z)

# division
z = x / y
# z = torch.div(x,y)
print(z)

tensor([[1.1950, 1.1364],
        [1.5633, 0.8317]])
tensor([[-0.5195,  0.0544],
        [-0.0476, -0.2656]])
tensor([[0.2896, 0.3221],
        [0.6104, 0.1553]])
tensor([[0.3940, 1.1005],
        [0.9409, 0.5159]])


We can also do the operations in-place.

In PyTorch, every in-place operation has a underscore `funcName_` attached.

In [23]:
# Initial 'y'
print(y)
# 'y' after addition, replaced in-place
y.add_(x)
# Final 'y'
print(y)

tensor([[0.8573, 0.5410],
        [0.8054, 0.5486]])
tensor([[1.1950, 1.1364],
        [1.5633, 0.8317]])


## 2.5 Slicing Tensors

In [25]:
x = torch.rand(5,3)
print(x)
print(x[:, 0]) # all rows, column 0
print(x[1, :]) # row 1, all columns
print(x[1,1]) # element at 1, 1

tensor([[0.5706, 0.8786, 0.1238],
        [0.5661, 0.2394, 0.0284],
        [0.1308, 0.6287, 0.5310],
        [0.5859, 0.9591, 0.8003],
        [0.5313, 0.0258, 0.6176]])
tensor([0.5706, 0.5661, 0.1308, 0.5859, 0.5313])
tensor([0.5661, 0.2394, 0.0284])
tensor(0.2394)


In [26]:
# Get the actual value if only 1 element in your tensor
print(x[1,1].item())

0.2394324541091919


## 2.6 Reshaping Tensors

In [27]:
# Reshape with torch.view()
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)
# the size -1 is inferred from other dimensions
# if -1, pytorch will automatically determine the necessary size
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


# 3. Converting Tensors to Numpy and vice-versa

## 3.1 Converting Tensors to Numpy Array

In [30]:
x_tensor = torch.ones(2,2)
print(x_tensor)
print(type(x_tensor))

tensor([[1., 1.],
        [1., 1.]])
<class 'torch.Tensor'>


In [31]:
x_numpy = x_tensor.numpy()
print(x_numpy)
print(type(x_numpy))

[[1. 1.]
 [1. 1.]]
<class 'numpy.ndarray'>


## 3.2 Converting Numpy Arrays to Tensors

In [33]:
x_tensor_new = torch.tensor(x_numpy)
print(x_tensor_new)
print(type(x_tensor_new))

tensor([[1., 1.],
        [1., 1.]])
<class 'torch.Tensor'>


**Caution:** While using GPU device for variables, it will give an error, if we want to convert the arrays to numpy and vice-versa. So, for this we have to make sure to use CPU.

# 4. Attaching `grad`

The `requires_grad` argument in the Tensors will tell PyTorch that it will need to calculate the gradients for this tensor, later in the optimization steps, i.e. this if this is a variable in the model that we want to optimize, we can extract it's gradient at any point.

In [24]:
x = torch.tensor([5.5, 3], requires_grad=True)
print(x)

tensor([5.5000, 3.0000], requires_grad=True)


# 5. Using GPU to store variables

By default all tensors are created on the CPU, but we can also move them to the GPU (only if it's available).

In [35]:
# since, we have apple metal GPU available, we have already set the device to 'MPS' in the imports cell above
device
# this is an MPS device object

device(type='mps')

In [37]:
# directly create a tensor on GPU
x = torch.ones((2,2), device=device)
print(x)

tensor([[1., 1.],
        [1., 1.]], device='mps:0')


In [39]:
x = torch.ones((2,2))
print(x)
# indirectly convert to a tensor on GPU
y = x.to(device)
print(y)

tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]], device='mps:0')


In [43]:
# we can't operate on variables present on two different devices
z = x + y

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, mps:0 and cpu!